### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by dlsniper** [narqo/go-badge#1]
Hi,

I've seen your request for CR on reddit so here it is.

Before that, congrats on the library, keep it Going :D 

Non code specifics:
- [x] there's no LICENSE file for this, so even if the README says it's MIT, one should be added, please see http://choosealicense.com/
- [x] the vendor directory shouldn't be commited. While I'm not sure about the Godeps one just yet (I don't know how it resolves the dependencies of the dependencies), the vendor one shouldn't be in here for sure
- [x] all the contents of `badge/` folder should be moved to the root directory so that the import path reads like this: `import "github.com/narqo/go-badge"` not `import "github.com/narqo/go-badge/badge"` (the package name can still be `badge`)

Code specifics:
- [x] https://github.com/narqo/go-badge/blob/1650d0cdc85951e530d6d9d96dfbd9bd735235f7/badge/badge.go#L27 the `data` that is sent to the template could (should) be a struct instead of a map[string]interface{} so that it can be extended cleaner in the future (and retain control over the type of the fileds). Plus at some point maybe the code editors will catch up with the templating language so that would further help out.
- [ ] while this one is a personal thing, I usually prefer to group out all the package level var / const declarations into a single one at the top of the package, followed by the `init` function. Don't take it as a hard rule I've seen code with both versions
- [x] I believe that the `init` function call chain can be "inlined" into one single init function containing all the code. As far as I can tell those functions are meant to be ran only one, at init time so might as well just have all the code (it's small enough) in one single function body
- [x] https://github.com/narqo/go-badge/blob/1650d0cdc85951e530d6d9d96dfbd9bd735235f7/badge/badge.go#L20 could be done in the `init()` function (if I read this correctly)
- [ ] since `type badgeDrawer struct` is not exported, this can be converted to a package level variables and then fruther simplify the package by not having a package function called `Render` which calls to the `badgeDrawer.Render`. While this can be kept there's no reuse functionality of it as far as I can think of. Otherwise this still works
- [ ] the code for the tests is missing. If you lack a proper test case for the render function, I could suggest just having a simple `demo` text rendered and compared to a `demo-badge.svg` which can be committed in the repository

And I think that's about it (at least on a very quick glance). Hope it helps.
Please let me know if you have any further questions (or ping me on the gophers-slack).

Kind regards.

**Comment by narqo** [comment]
Thanks @dlsniper for such a detailed review! I totally agree with your points and will fix the code soon.
